apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo-controller
  template:
    metadata:
      labels:
        app: foo-controller
    spec:
      containers:
      - name: foo-controller
        image: < IMAGE REPO >/crd-demo
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: 128Mi
              cpu: 250m
      - name: leader-election
        image: fredrikjanssonse/leader-elector:0.6
        args:
        - --election=foo-election
        - --http=0.0.0.0:4040
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4040
        resources:
            limits:
              memory: 128Mi
              cpu: 250m