apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dbs.samples.k8s-cs-controller
spec:
  group: samples.k8s-cs-controller
  version: v1
  subresources:
    status: {}
  scope: Namespaced
  names:
    plural: dbs
    singular: db
    kind: MSSQLDB
  validation:
    openAPIV3Schema:
      type: object
      description: "A Microsoft SQLServer Database"
      properties:
        spec:
          type: object
          properties:
            dbname:
              type: string
          required: ["dbname"]