name: Docker

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/docker-publish.yml
      - src/samples/msssql-db/

env:
  config: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: sebagomez
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sebagomez/k8s-mssqldb
        tags: latest
        path: ./src/samples/mssql-db
        push: true 
