name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  config: Release
  nugetServer: https://api.nuget.org/v3/index.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore  src/k8s-controller-sdk/k8s-controller-sdk.csproj
    - name: Build
      run: dotnet build --configuration $config --no-restore  src/k8s-controller-sdk/k8s-controller-sdk.csproj
    - name: Package
      run: dotnet pack --configuration $config --no-build  --output ./bin src/k8s-controller-sdk/k8s-controller-sdk.csproj
    - name: Publish
      env: 
        nuget_apikey: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push .\bin\Kubernetes.Controller.SDK.1.0.0.nupkg -k $nuget_apikey -s $nugetServer
 